# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Helm tool installer
        uses: Azure/setup-helm@v3          
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      - name: Install Chart 
        run: helm install myapp mychart 
      - name: Wait Timer 
        uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '1m' # for 1 minute
      - name: kubectl
        run: kubectl get pods -A 
      - name: Port Forwarding 
        run: |
          export POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}') 
          echo $POD_NAME
          export NODE_PORT=$(kubectl get --namespace default -o jsonpath="{.spec.ports[0].nodePort}" services mynginx)
          echo $NODE_PORT
          kubectl port-forward $POD_NAME 8080:$NODE_PORT
          curl -s http://127.0.0.1:8080
      # - name: Port Forwarding 
      #   run: |
      #     export POD_NAME=$(kubectl get pods -l "app.kubernetes.io/name=mychart,app.kubernetes.io/instance=mynginx" -o jsonpath="{.items[0].metadata.name}")
      #     export NODE_PORT=$(kubectl get --namespace default -o jsonpath="{.spec.ports[0].nodePort}" services mynginx)
      #     kubectl port-forward $POD_NAME 8080:$NODE_PORT
      #     curl -s http://127.0.0.1:8080
      # - name: kubectl deployment
      #   run: kubectl create deployment kubernetes-bootcamp --image=nginx
      # - name: kubectl
      #   run: kubectl get pods -A
      # - name: kubectl
      #   run: kubectl create svc nodeport my-ns --tcp=5678:80
      # - name: Test service URLs
      #   run: |
      #     minikube service list
      #     minikube service discover --url
      
